// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egyohldpngjylxsjirha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVneW9obGRwbmdqeWx4c2ppcmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzkwNjUsImV4cCI6MjA2MDA1NTA2NX0.O3uwK8ysorLGKJgdagz-iqaslt8-CwfTeLi5m1Zv-Vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);