
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://jljmsufkiemvgodqexqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsam1zdWZraWVtdmdvZHFleHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NjU3NjMsImV4cCI6MjA2MDM0MTc2M30.fjj162LCbXAif-G_jkVvi5YlORESp-cnALOgtuk4kvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Generate types with: npx supabase gen types typescript --project-id "jljmsufkiemvgodqexqh" --schema public > src/types/supabase.ts
